title: RamMap Task Scheduler
description: >
  Windows batch script to create scheduled tasks for RAMMap
  
show_excerpts: false

minima:
  date_format: "%b %-d, %Y"
  
  social_links:
    twitter: _Nimbi
    github:  NimbiDev
    
theme: minima
markdown: kramdown

plugins:
 - jekyll-feed
 - jekyll-seo-tag
