title: RamMap Task Scheduler
author:
  name: PhantomNimbi
  email: JoshuaVL1988@protonmail.com
description: >
  Windows batch script to create scheduled tasks for RAMMap
baseurl: ./_docs
  
show_excerpts: false

minima:
  date_format: "%b %-d, %Y"
  
  social_links:
    twitter: _Nimbi
    github:  NimbiDev
    
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
